# Generated by Django 4.1 on 2022-09-28 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0004_taskassign'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskAssign',
        ),
        migrations.DeleteModel(
            name='Work',
        ),
    ]
