# Generated by Django 4.1 on 2022-09-28 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0006_taskassign_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassign',
            name='task_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.work'),
        ),
    ]
