# Generated by Django 4.1 on 2022-09-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0008_datacollect'),
    ]

    operations = [
        migrations.CreateModel(
            name='TLDProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tld_date', models.DateField(blank=True, null=True)),
                ('tld_project_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
