# Generated by Django 4.1 on 2022-09-30 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0010_tldpojectdescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='TLDProjectReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tld_project_review_date', models.DateField(blank=True, null=True)),
                ('tld_project_reviewid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.tldproject')),
            ],
        ),
    ]
