# Generated by Django 4.1 on 2022-09-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0012_tldprojectcorrectionupdation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tldprojectcorrectionupdation',
            name='tld_project_cu_end',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tldprojectcorrectionupdation',
            name='tld_project_cu_start',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
