# Generated by Django 3.2.12 on 2022-04-07 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0012_project_taskassign_delay'),
    ]

    operations = [
        migrations.CreateModel(
            name='previousTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pstatus', models.CharField(max_length=200)),
                ('teamname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teamname', to='base_app.create_team')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user1', to='base_app.user_registration')),
            ],
        ),
    ]
