# Generated by Django 4.1 on 2022-09-30 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0013_alter_tldprojectcorrectionupdation_tld_project_cu_end_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TLDProjectCorrectionUpdation',
        ),
    ]
