# Generated by Django 3.2.12 on 2022-04-14 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0013_previousteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='acnt_monthdays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_fromdate', models.DateField(blank=True, null=True)),
                ('month_todate', models.DateField(blank=True, null=True)),
                ('month_workingdays', models.IntegerField()),
                ('month_holidays', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='internship_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('fee', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='acntspayslip',
            name='pending_status',
            field=models.CharField(default='0', max_length=25),
        ),
        migrations.AddField(
            model_name='internship',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='internship',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='internship',
            name='complete_status',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='internship',
            name='pay_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='total_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='internship',
            name='total_pay',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='internship',
            name='verify_status',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='previousteam',
            name='progress',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='confirm_salary',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='confirm_salary_status',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='payment_amount_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='payment_file_downlod',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='salary_pending',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='salary_status',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='total_amount',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='trainer_level',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='acntspayslip',
            name='basic_salary',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='acntspayslip',
            name='delay',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='acntspayslip',
            name='hra',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='acntspayslip',
            name='incentives',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='acntspayslip',
            name='incometax',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='acntspayslip',
            name='leavesno',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='acntspayslip',
            name='pf',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='acntspayslip',
            name='pf_tax',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='acntspayslip',
            name='tax',
            field=models.IntegerField(default='0'),
        ),
        migrations.CreateModel(
            name='Promissory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inital_amount', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('inital_paid_on', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('inital_paid_amount', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('inital_paid_date', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('inital_balance_amount', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('inital_due_date', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('inital_total_payment', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('second_amount', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('second_due_on', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('second_paid_amount', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('second_paid_date', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('second_balance_amount', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('second_due_date', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('second_total_payment', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('final_amount', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('final_due_on', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('final_paid_amount', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('final_paid_date', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('final_balance_amount', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('final_due_date', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('final_total_payment', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('complete_status', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promissory_user', to='base_app.user_registration')),
            ],
        ),
        migrations.CreateModel(
            name='internship_paydata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('internship_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internship_user', to='base_app.internship')),
            ],
        ),
        migrations.AddField(
            model_name='internship',
            name='internshiptype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internship_type', to='base_app.internship_type'),
        ),
    ]
