# Generated by Django 3.2.12 on 2022-04-21 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0014_auto_20220415_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_team',
            name='trainer_id',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
