# Generated by Django 4.1 on 2022-10-03 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0015_tldprojectcorrectionupdation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TLDProjectWorkers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tld_pw_date', models.DateField(blank=True, null=True)),
                ('tld_pw_workdays', models.IntegerField()),
                ('tld_pw_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.tldproject')),
                ('tld_pwn_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.user_registration')),
            ],
        ),
    ]
