# Generated by Django 3.2.12 on 2022-04-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0015_create_team_trainer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='hr_designation',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
    ]
