# Generated by Django 4.1 on 2022-10-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0016_tldprojectworkers'),
    ]

    operations = [
        migrations.AddField(
            model_name='tldprojectworkers',
            name='tld_pw_wid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
