# Generated by Django 4.1 on 2022-10-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0017_tldprojectworkers_tld_pw_wid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tldprojectworkers',
            name='tld_pw_wid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
