# Generated by Django 3.2.12 on 2022-04-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0017_auto_20220427_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer_task',
            name='task_progress',
            field=models.IntegerField(default=0),
        ),
    ]
