# Generated by Django 4.1 on 2022-10-05 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0018_alter_tldprojectworkers_tld_pw_wid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectdoc_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.project')),
                ('projectdoc_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.work')),
            ],
        ),
    ]
