# Generated by Django 3.2.12 on 2022-04-28 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0019_probation'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer_task',
            name='delay',
            field=models.IntegerField(default=0),
        ),
    ]
