# Generated by Django 4.1 on 2022-10-05 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0019_projectdocuments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdocuments',
            name='projectdoc_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.user_registration'),
        ),
    ]
