# Generated by Django 4.1 on 2022-10-05 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0020_alter_projectdocuments_projectdoc_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tldprojectcorrectionupdation',
            name='tld_project_cu_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.project'),
        ),
        migrations.AlterField(
            model_name='tldprojectreview',
            name='tld_project_reviewid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.project'),
        ),
        migrations.AlterField(
            model_name='tldprojectworkers',
            name='tld_pw_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.project'),
        ),
        migrations.DeleteModel(
            name='TLDPojectDescription',
        ),
        migrations.DeleteModel(
            name='TLDProject',
        ),
    ]
