# Generated by Django 3.2.12 on 2022-05-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0021_project_module_assign_project_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='acntspayslip',
            name='net_salary',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
