# Generated by Django 3.2.12 on 2022-05-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0022_acntspayslip_net_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='acntspayslip',
            name='da',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
