# Generated by Django 4.1 on 2022-10-05 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0022_pm_projectdocumentdetails_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TLDProjectCorrectionUpdation',
        ),
    ]
