# Generated by Django 3.2.12 on 2022-05-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0023_acntspayslip_da'),
    ]

    operations = [
        migrations.AddField(
            model_name='acntspayslip',
            name='account_no',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='acntspayslip',
            name='bank_branch',
            field=models.CharField(default='', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='acntspayslip',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='acntspayslip',
            name='ifsc',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
