# Generated by Django 3.2.12 on 2022-05-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0024_auto_20220513_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leaveapprovedstatus',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
