# Generated by Django 4.1 on 2022-10-05 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0024_projectcorrectionupdation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectCorrectionUpdation',
        ),
    ]
