# Generated by Django 3.2.12 on 2022-05-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0025_alter_leave_leaveapprovedstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='acntspayslip',
            name='other_allovance',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='acntspayslip',
            name='other_allovancetype',
            field=models.CharField(default='', max_length=255),
        ),
    ]
