# Generated by Django 3.2.12 on 2022-05-21 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0026_auto_20220514_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_head',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_head', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('description_paymenthead', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_date', models.DateField(blank=True, null=True)),
                ('party_name', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('pay_method', models.CharField(blank=True, max_length=255, null=True)),
                ('pay_description', models.TextField(blank=True, default='', null=True)),
                ('pay_status', models.IntegerField(default=0)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_department_name', to='base_app.department')),
                ('payment_head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_payment_head', to='base_app.payment_head')),
            ],
        ),
    ]
