# Generated by Django 4.1 on 2022-10-05 13:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0026_projectcorrectionupdation'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='projectcorrectionupdation',
            name='project_cu_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectcorrectionupdation',
            name='project_cu_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectcorrectionupdation',
            name='project_cu_wdays',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
