# Generated by Django 4.1 on 2022-10-05 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0027_projectcorrectionupdation_project_cu_current_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectCorrectionUpdation',
        ),
    ]
