# Generated by Django 3.2.12 on 2022-06-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0028_leave_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='promissory',
            name='final_due_date_on',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='promissory',
            name='second_due_date_on',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='confirm_salary',
            field=models.CharField(default='', max_length=10),
        ),
    ]
