# Generated by Django 3.2.12 on 2022-06-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0029_auto_20220627_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promissory',
            name='final_total_payment',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='inital_total_payment',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='second_total_payment',
            field=models.IntegerField(default='0'),
        ),
    ]
