# Generated by Django 4.1 on 2022-10-05 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0029_projectcorrectionupdation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectCorrectionUpdation',
        ),
    ]
