# Generated by Django 3.2.15 on 2022-09-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0030_auto_20220627_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_taskassign',
            name='workaccept',
            field=models.FileField(blank=True, default='0', null=True, upload_to='images/'),
        ),
    ]
