# Generated by Django 4.1 on 2022-10-05 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0031_projectcorrectionupdation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcorrectionupdation',
            name='project_cu_review_id',
        ),
    ]
