# Generated by Django 4.1 on 2023-03-10 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0032_alter_project_description'),
    ]

    operations = [
       
        
       
       
       
       
       
       
       
    ]
