# Generated by Django 4.1 on 2022-10-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0032_alter_project_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DM_projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dm_date', models.DateField(auto_now_add=True, null=True)),
                ('dm_project_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dm_project_categ', models.CharField(blank=True, max_length=150, null=True)),
                ('dm_project_status', models.CharField(blank=True, default='Not Started', max_length=50, null=True)),
            ],
        ),
    ]
