# Generated by Django 4.1 on 2022-10-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0033_dm_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='dm_projects',
            name='dm_project_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
