# Generated by Django 4.1 on 2022-10-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0033_projectworkers_delete_tldprojectworkers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectworkers',
            name='pw_wid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
