# Generated by Django 4.1 on 2023-03-10 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0033_batch_dm_project_task_dm_projects_usermanuvel_and_more'),
    ]

    operations = [
        
       
    ]
