# Generated by Django 4.1 on 2022-10-07 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0034_alter_projectworkers_pw_wid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tldprojectreview',
            name='tld_project_reviewid',
        ),
        migrations.AlterField(
            model_name='pm_projectdocumentdetails',
            name='doc_project_ui',
            field=models.FileField(null=True, upload_to='ProjectUI'),
        ),
        migrations.DeleteModel(
            name='ProjectDocuments',
        ),
        migrations.DeleteModel(
            name='TLDProjectReview',
        ),
    ]
