# Generated by Django 4.1 on 2022-10-15 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0034_dm_projects_dm_project_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dm_project_Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dm_task_assigndate', models.DateField(auto_now_add=True, null=True)),
                ('dm_task_status', models.CharField(blank=True, max_length=100, null=True)),
                ('dm_project_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.dm_projects')),
                ('dm_user_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.user_registration')),
            ],
        ),
    ]
