# Generated by Django 4.1 on 2022-10-07 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0035_remove_tldprojectreview_tld_project_reviewid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDeveloperDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_ui_date', models.DateField(blank=True, null=True)),
                ('project_ui_design', models.FileField(null=True, upload_to='ProjectUI')),
                ('ui_project_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.project')),
            ],
        ),
    ]
