# Generated by Django 4.1 on 2023-03-17 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0036_leads_register'),
    ]

    operations = [
      
        migrations.AddField(
            model_name='leads_register',
            name='r_assing_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_assign', to='base_app.user_registration'),
        ),
       
    ]
