# Generated by Django 4.1 on 2022-10-17 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0036_dm_project_task_dm_task_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCollect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dc_date', models.DateField(blank=True, null=True)),
                ('dc_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dc_email', models.CharField(blank=True, max_length=100, null=True)),
                ('dc_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('dc_loc', models.CharField(blank=True, max_length=110, null=True)),
                ('dc_internship', models.CharField(blank=True, max_length=100, null=True)),
                ('dc_Fr_Ex', models.CharField(blank=True, max_length=50, null=True)),
                ('dc_status', models.CharField(blank=True, max_length=50, null=True)),
                ('dc_reason', models.CharField(blank=True, max_length=50, null=True)),
                ('Employeeid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.user_registration')),
                ('Project_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.dm_projects')),
            ],
        ),
    ]
