# Generated by Django 4.1 on 2022-10-08 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0036_projectdeveloperdesign'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='taskassign',
            name='task_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
