# Generated by Django 4.1 on 2022-10-08 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0037_alter_taskassign_employee_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskAssign',
        ),
    ]
