# Generated by Django 4.1 on 2022-10-10 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0039_taskassign'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcorrectionupdation',
            name='pdev_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.user_registration'),
        ),
    ]
