# Generated by Django 4.1 on 2023-03-23 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0039_batch_dm_project_task_dm_projects_usermanuvel_and_more'),
    ]

    operations = [
    
        migrations.AddField(
            model_name='project_taskassign',
            name='tsakdelaydays',
            field=models.IntegerField(default='0', null=True),
        ),
       
    ]