# Generated by Django 4.1 on 2022-10-10 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0040_projectcorrectionupdation_pdev_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectWorkers',
        ),
    ]
