# Generated by Django 4.1 on 2022-10-10 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0041_delete_projectworkers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectWorkers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pw_startdate', models.DateField(blank=True, null=True)),
                ('pw_enddate', models.DateField(blank=True, null=True)),
                ('pw_wid', models.CharField(blank=True, max_length=50, null=True)),
                ('pw_workdays', models.IntegerField()),
                ('pw_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.pm_projectdocumentdetails')),
                ('pwn_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.user_registration')),
            ],
        ),
    ]
