# Generated by Django 4.1 on 2022-10-17 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0042_clientdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_date', models.DateField(blank=True, null=True)),
                ('op_url', models.URLField()),
                ('op_work', models.TextField()),
                ('op_status', models.CharField(blank=True, max_length=50, null=True)),
                ('op_Employeeid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.user_registration')),
                ('op_taskid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.dm_project_task')),
            ],
        ),
    ]
