# Generated by Django 4.1 on 2023-03-30 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0042_batch_dm_project_task_dm_projects_usermanuvel_and_more'),
    ]

    operations = [

        migrations.CreateModel(
            name='LeadExtradata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_ex_head', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('lead_ex_data', models.TextField(default='')),
                ('leadid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_id', to='base_app.leads_register')),
            ],
        ),
       
    ]
