# Generated by Django 4.1 on 2022-10-11 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0042_projectworkers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDocAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docstatus', models.CharField(blank=True, max_length=50, null=True)),
                ('tl_docproject_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.project')),
                ('tl_docprojectco_up', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.projectcorrectionupdation')),
                ('tl_docprojectdetail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.pm_projectdocumentdetails')),
                ('tl_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.user_registration')),
            ],
        ),
    ]
