# Generated by Django 4.1 on 2022-10-11 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0043_projectdocassign'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevprojectDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devassign_date', models.DateField(auto_now_add=True, null=True)),
                ('devstatus', models.CharField(blank=True, default='Not Assigned', max_length=50, null=True)),
                ('devprdoc_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.projectdocassign')),
            ],
        ),
    ]
