# Generated by Django 4.1 on 2022-10-17 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0043_onpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCalander',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_date', models.DateField(blank=True, null=True)),
                ('blog_title', models.CharField(blank=True, max_length=50, null=True)),
                ('blog_key', models.TextField()),
                ('blog_status', models.CharField(blank=True, max_length=50, null=True)),
                ('blog_Employeeid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.user_registration')),
                ('blog_taskid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.dm_project_task')),
            ],
        ),
    ]
