# Generated by Django 4.1 on 2022-10-11 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0044_devprojectdoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='devprojectdoc',
            name='dv_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.user_registration'),
        ),
    ]
