# Generated by Django 4.1 on 2023-05-25 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0044_batch_dm_project_task_dm_projects_usermanuvel_and_more'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='project_taskassign',
            name='tester_delay',
            field=models.CharField(default='0', max_length=200, null=True),
        ),
        
    ]
