# Generated by Django 4.1 on 2022-10-19 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0045_smmposter'),
    ]

    operations = [
        migrations.CreateModel(
            name='DM_Project_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(auto_now_add=True, null=True)),
                ('re_project_name', models.CharField(blank=True, max_length=100, null=True)),
                ('re_project_task', models.CharField(blank=True, max_length=150, null=True)),
                ('re_project_task_file', models.FileField(default=None, null=True, upload_to='report')),
                ('report_project_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.dm_projects')),
            ],
        ),
    ]
