# Generated by Django 4.1 on 2022-10-12 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0045_devprojectdoc_dv_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectworkers',
            name='pwscu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.projectcorrectionupdation'),
        ),
    ]
