# Generated by Django 4.1 on 2023-07-25 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0046_batch_dm_project_task_dm_projects_usermanuvel_and_more'),
    ]

    operations = [
      
        migrations.CreateModel(
            name='Certificate_approve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cf_certificate', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('cf_request_date', models.DateField(auto_now_add=True, null=True)),
                ('cf_approve_date', models.DateField(blank=True, null=True)),
                ('cf_status', models.IntegerField(blank=True, default=0, null=True)),
                ('cf_develp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Certificate_user', to='base_app.user_registration')),
            ],
        ),
        
    ]
