# Generated by Django 4.1 on 2022-10-22 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0047_dm_project_report_re_project_dese_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DM_project_dese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dm_task_date', models.DateField(auto_now_add=True, null=True)),
                ('dm_task_dese', models.TextField()),
                ('dm_task_project_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.dm_projects')),
            ],
        ),
    ]
