# Generated by Django 4.1 on 2022-10-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0049_tsproject_task_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsproject_task_verify',
            name='ts_delay',
            field=models.CharField(default='0', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tsproject_task_verify',
            name='ts_reson_dely',
            field=models.TextField(default=''),
        ),
    ]
