# Generated by Django 4.1 on 2022-10-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0051_tsproject_task_verify_ts_tester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsproject_task_verify',
            name='ts_task_status',
            field=models.CharField(default='0', max_length=200, null=True),
        ),
    ]
