# Generated by Django 4.1 on 2022-10-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0052_tsproject_task_verify_ts_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tsproject_task_verify',
            name='ts_task_status',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
