# Generated by Django 4.1 on 2022-10-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0053_alter_tsproject_task_verify_ts_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='employee_type',
            field=models.CharField(default='0', max_length=20, null=True),
        ),
    ]
