# Generated by Django 4.1 on 2022-10-28 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0054_user_registration_employee_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PM_ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_project_name', models.CharField(blank=True, max_length=100, null=True)),
                ('doc_project_currentdate', models.DateField(auto_now_add=True, null=True)),
                ('doc_project_startdate', models.DateField(blank=True, null=True)),
                ('doc_project_enddate', models.DateField(blank=True, null=True)),
                ('doc_project_frontend', models.CharField(blank=True, max_length=100, null=True)),
                ('doc_project_backend', models.CharField(blank=True, max_length=100, null=True)),
                ('doc_project_ui', models.FileField(null=True, upload_to='ProjectUI')),
                ('doc_project_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.project')),
            ],
        ),
    ]
