# Generated by Django 4.1 on 2022-10-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0055_pm_projectdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='pm_projectdocument',
            name='doc_status',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
    ]
