# Generated by Django 4.1 on 2022-10-28 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0056_pm_projectdocument_doc_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PM_ProjectDoc_Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_project_md_name', models.CharField(blank=True, max_length=100, null=True)),
                ('doc_project_md_dese', models.TextField()),
                ('doc_projectdocd_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.project')),
            ],
        ),
    ]
