# Generated by Django 4.1 on 2022-10-28 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0057_pm_projectdoc_module'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PM_ProjectDoc_Module',
        ),
    ]
