# Generated by Django 4.1 on 2022-10-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0059_projectcorrectionupdation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcorrectionupdation',
            name='pdev_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='projectcorrectionupdation',
            name='project_cu_wdays',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
