# Generated by Django 4.1 on 2022-10-29 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0060_alter_projectcorrectionupdation_pdev_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcorrectionupdation',
            name='ptl_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='projectcorrectionupdation',
            name='pdev_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
