# Generated by Django 4.1 on 2022-10-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0061_projectcorrectionupdation_ptl_name_and_more'),
    ]

   
