# Generated by Django 4.1 on 2022-10-29 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0062_project_taskassign_module'),
    ]

    