# Generated by Django 4.1 on 2022-10-31 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0063_remove_project_taskassign_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='wrdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrn_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('wrn_date', models.DateField(auto_now_add=True, null=True)),
                ('wrn_develp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wr_devp', to='base_app.user_registration')),
                ('wrn_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wr_task', to='base_app.project_taskassign')),
                ('wrn_user_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wr_user', to='base_app.user_registration')),
            ],
        ),
    ]
