# Generated by Django 4.1 on 2022-11-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0066_projectdochtmlpages_doc_project_html_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdochtmlpages',
            name='doc_project_hpmdname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
