# Generated by Django 4.1 on 2022-11-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0067_projectdochtmlpages_doc_project_hpmdname'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_taskassign',
            name='worktype',
            field=models.CharField(default='0', max_length=15, null=True),
        ),
    ]
