# Generated by Django 4.1 on 2022-11-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0068_project_taskassign_worktype'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='work_status',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
