# Generated by Django 4.1 on 2022-11-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0069_user_registration_work_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registration',
            name='alternativeno',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='employee_type',
            field=models.CharField(default='0', max_length=15, null=True),
        ),
    ]
