# Generated by Django 4.1 on 2022-11-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0070_alter_user_registration_alternativeno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registration',
            name='work_status',
            field=models.CharField(default='Null', max_length=10),
        ),
    ]
