# Generated by Django 4.1 on 2022-11-04 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0071_alter_user_registration_work_status'),
    ]

    operations = [
      
    ]
