# Generated by Django 4.1 on 2022-11-05 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0073_alter_user_registration_work_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer_task',
            name='task_type',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
