# Generated by Django 4.1 on 2022-11-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0076_batch_trainee_trainerfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_team',
            name='bt_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
