# Generated by Django 4.1 on 2022-11-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0077_create_team_bt_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='previousteam',
            name='tr_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='previousteam',
            name='tr_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
