# Generated by Django 4.1 on 2022-11-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0078_previousteam_tr_end_date_previousteam_tr_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsproject_task_verify',
            name='ts_task_sub_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
