# Generated by Django 4.1 on 2022-11-10 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0079_tsproject_task_verify_ts_task_sub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrkreq_date', models.DateField(auto_now_add=True, null=True)),
                ('wrk_status', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('wrk_develp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wrk_devp', to='base_app.user_registration')),
            ],
        ),
    ]
