# Generated by Django 4.1 on 2022-11-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0082_project_taskassign_projmodule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='uifile',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
