# Generated by Django 4.1 on 2022-11-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0084_alter_project_table_module_name_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_table',
            name='module_name_id',
            field=models.IntegerField(default='0'),
        ),
    ]
