# Generated by Django 4.1 on 2022-11-11 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0085_alter_project_table_module_name_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_table',
            name='module_name_id',
        ),
    ]
