# Generated by Django 4.1 on 2022-11-12 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0089_rename_fb_trinee_feedbacks_fb_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action_Taken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_remark', models.TextField()),
                ('at_date', models.DateField(auto_now_add=True, null=True)),
                ('at_status', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('atdep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depat', to='base_app.department')),
                ('atdesig', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desigat', to='base_app.designation')),
                ('atemp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empat', to='base_app.user_registration')),
            ],
        ),
    ]
