# Generated by Django 4.1 on 2022-11-14 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0090_action_taken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary_hold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hddate', models.DateField(auto_now_add=True, null=True)),
                ('sal_reason', models.TextField()),
                ('sal_amount', models.IntegerField(default=0, null=True)),
                ('sal_status', models.CharField(default='', max_length=50)),
                ('sal_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salarys', to='base_app.acntspayslip')),
            ],
        ),
    ]
