# Generated by Django 4.1 on 2022-11-14 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0091_salary_hold'),
    ]

    operations = [
        migrations.AddField(
            model_name='action_taken',
            name='atby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ationby', to='base_app.user_registration'),
        ),
    ]
