# Generated by Django 4.1 on 2022-11-16 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0092_action_taken_atby'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserManuvel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('um_head', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('um_subhead', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('um_dese', models.TextField()),
                ('um_date', models.DateField(auto_now_add=True, null=True)),
                ('um_files', models.FileField(blank=True, null=True, upload_to='images/')),
                ('user_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usermanuvel', to='base_app.project')),
            ],
        ),
        migrations.CreateModel(
            name='UserManuvelPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('um_points', models.TextField()),
                ('user_manuvelid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usermanuvelid', to='base_app.usermanuvel')),
                ('userp_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='umproj', to='base_app.project')),
            ],
        ),
    ]
