# Generated by Django 4.1 on 2022-11-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0093_usermanuvel_usermanuvelpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermanuvelpoints',
            name='um_pfiles',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
