# Generated by Django 4.1 on 2022-11-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0094_usermanuvelpoints_um_pfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_taskassign',
            name='tsakworkdays',
            field=models.IntegerField(default='0', null=True),
        ),
    ]
