# Generated by Django 4.1 on 2022-11-17 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0095_project_taskassign_tsakworkdays'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBudgect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pb_date', models.DateField(auto_now_add=True, null=True)),
                ('pb_title', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('pb_status', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('pb_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('pb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pbug', to='base_app.project')),
            ],
        ),
    ]
