# Generated by Django 4.1 on 2022-11-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0097_projectbudgect_pb_compdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbudgect',
            name='pbtotal_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
