# Generated by Django 4.1 on 2022-11-18 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0098_projectbudgect_pbtotal_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectbudgect',
            name='pbtotal_amount',
        ),
    ]
