# Generated by Django 4.1 on 2022-11-18 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0099_remove_projectbudgect_pbtotal_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcorrectionupdation',
            name='project_tsak_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.project_taskassign'),
        ),
    ]
