# Generated by Django 4.1 on 2022-11-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0100_projectcorrectionupdation_project_tsak_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='desig_input',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
