# Generated by Django 4.1 on 2022-11-23 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0102_alter_user_registration_desig_input'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_registration',
            name='desig_input',
        ),
    ]
