# Generated by Django 4.1 on 2022-11-23 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0104_user_registration_desig_input'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer_Task_Correction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correctiondate', models.DateField(auto_now_add=True, null=True)),
                ('correction_description', models.TextField(max_length=240)),
                ('correctionfiles', models.FileField(blank=True, null=True, upload_to='images/')),
                ('task_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_task', to='base_app.trainer_task')),
            ],
        ),
    ]
