# Generated by Django 4.1 on 2022-12-07 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0105_trainer_task_correction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_registration',
            name='desig_input',
        ),
    ]
