# Generated by Django 4.1 on 2023-02-25 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0109_leads_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads_register',
            name='r_type',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='leads_register',
            name='r_type_status',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
