# Generated by Django 4.1 on 2023-03-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0111_leads_register_r_lead_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads_register',
            name='r_fre_exp',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
